services:
  godoist:
    build:
      context: ..
      dockerfile: automadoist/Dockerfile
    command: --config /config.yaml --debug next_items 
    volumes:
      - ./config.yaml:/config.yaml
    env_file:
      - .env

  cron:
    build:
      context: ..
      dockerfile: automadoist/Dockerfile.cron
    environment:
      - CRON_TODOIST=*/15 * * * * /automadoist --config /config.yaml --debug next_items 
      - GODOIST_TOKEN=${GODOIST_TOKEN}
    volumes:
      - ./config.yaml:/config.yaml
